In [1]:
import pandas as pd
import numpy as np
clean_reviews = pd.read_csv('./data/Hotel_Reviews.csv')

In [2]:
# checking null values for latitude and longitude field
clean_reviews.lat.isnull().values.any()
clean_reviews.lng.isnull().values.any()

True

In [3]:
#removing empty or null values form columns Latitude and Longitude columns
clean_reviews = clean_reviews[np.isfinite(clean_reviews['lat'])]
clean_reviews = clean_reviews[np.isfinite(clean_reviews['lng'])]

In [4]:
# making new dataframe which consists of unique hotels with latitude and longitude fields and taking average of reviewer_Score
Hotel_And_Score = clean_reviews.groupby(['Hotel_Name','lat','lng'])['Reviewer_Score'].mean()

In [5]:
Hotel_And_Score

Hotel_Name                                           lat        lng
11 Cadogan Gardens                                   51.493616  -0.159235     8.845283
1K Hotel                                             48.863932   2.365874     7.861486
25hours Hotel beim MuseumsQuartier                   48.206474   16.354630    8.983309
41                                                   51.498147  -0.143649     9.711650
45 Park Lane Dorchester Collection                   51.506371  -0.151536     9.603571
88 Studios                                           51.499279  -0.209073     8.489107
9Hotel Republique                                    48.870842   2.360586     8.743716
A La Villa Madame                                    48.848861   2.331526     8.853659
ABaC Restaurant Hotel Barcelona GL Monumento         41.410694   2.136294     8.464516
AC Hotel Barcelona Forum a Marriott Lifestyle Hotel  41.410131   2.218805     8.001384
AC Hotel Diagonal L Illa a Marriott Lifestyle Hotel  41.389961   2.135684     8.398214
AC Hotel Irla a Marriott Lifestyle Hotel             41.394818   2.143470     8.125000
AC Hotel Milano a Marriott Lifestyle Hotel           45.485180   9.183119     8.202778
AC Hotel Paris Porte Maillot by Marriott             48.882005   2.281854     8.425333
AC Hotel Sants a Marriott Lifestyle Hotel            41.377558   2.138469     7.921978
AC Hotel Victoria Suites a Marriott Lifestyle Hotel  41.389348   2.120976     8.828889
ADI Doria Grand Hotel                                45.485372   9.211584     8.388435
ADI Hotel Poliziano Fiera                            45.483717   9.164937     8.042991
ARCOTEL Kaiserwasser Superior                        48.231915   16.417026    8.465035
ARCOTEL Wimberger                                    48.200600   16.338633    7.947651
AZIMUT Hotel Vienna                                  48.183479   16.376277    8.269880
Abba Garden                                          41.385472   2.101884     8.037600
Abba Sants                                           41.382578   2.140010     8.368333
Acad mie H tel Saint Germain                         48.855263   2.330590     9.064706
Acca Palace                                          45.509997   9.173994     8.590909
Ace Hotel London Shoreditch                          51.525416  -0.077285     8.683074
Acevi Villarroel                                     41.385378   2.156723     7.651420
Acta Atrium Palace                                   41.390913   2.170698     8.650437
Acta CITY47                                          41.383515   2.140740     8.185039
Admiral Hotel                                        45.480515   9.160063     7.130769
                                                                                ...
Vincci Gala                                          41.389526   2.174714     8.742515
Vincci Mae                                           41.393394   2.146132     8.995283
Vincci Maritimo                                      41.408205   2.212463     8.210787
W Amsterdam                                          52.372787   4.890006     8.303271
W Barcelona                                          41.368437   2.190153     8.412348
W London Leicester Square                            51.510843  -0.131429     8.312360
W Paris Op ra                                        48.871970   2.331601     8.307500
W12 Rooms                                            51.504533  -0.219117     8.745926
Waldorf Astoria Amsterdam                            52.364768   4.896945     9.535211
Waldorf Madeleine                                    48.871583   2.322485     8.608541
Warwick Paris Former Warwick Champs Elysees          48.872202   2.303087     8.073236
Washington Mayfair Hotel                             51.506024  -0.151078     7.909442
WestCord Art Hotel Amsterdam 4 stars                 52.392490   4.868382     8.629764
WestCord Fashion Hotel Amsterdam                     52.357655   4.844576     8.896554
Westside Arc de Triomphe Hotel                       48.881174   2.294834     8.165529
Wilson Boutique Hotel                                41.394403   2.150194     8.782759
Windermere Hotel                                     51.490372  -0.145922     8.950526
Windsor Hotel Milano                                 45.479459   9.195143     8.285977
Windsor Opera                                        48.873485   2.348511     8.088235
Worldhotel Cristoforo Colombo                        45.475884   9.205791     8.538477
XO Hotel                                             48.882749   2.298278     8.823077
Zenit Barcelona                                      41.394920   2.146859     8.081013
Zenit Borrell                                        41.385987   2.151402     7.590476
art otel Amsterdam                                   52.377743   4.897057     8.989114
citizenM Amsterdam                                   52.341943   4.875960     8.770289
citizenM London Bankside                             51.505151  -0.100472     9.112261
citizenM London Shoreditch                           51.524137  -0.078698     9.092005
citizenM Tower of London                             51.510237  -0.076443     9.135591
every hotel Piccadilly                               51.510146  -0.131506     8.967782
pentahotel Vienna                                    48.189974   16.356701    8.363566
Name: Reviewer_Score, Length: 1477, dtype: float64

In [6]:
#Currently Hotel name column is index of hotel_and_score dataframe by using reset_index index field will be resetted.
Hotel_And_Score = Hotel_And_Score.to_frame().reset_index()
Hotel_And_Score

,Hotel_Name,lat,lng,Reviewer_Score
0,11 Cadogan Gardens,51.493616,-0.159235,8.845283
1,1K Hotel,48.863932,2.365874,7.861486
2,25hours Hotel beim MuseumsQuartier,48.206474,16.354630,8.983309
3,41,51.498147,-0.143649,9.711650
4,45 Park Lane Dorchester Collection,51.506371,-0.151536,9.603571
5,88 Studios,51.499279,-0.209073,8.489107
6,9Hotel Republique,48.870842,2.360586,8.743716
7,A La Villa Madame,48.848861,2.331526,8.853659
8,ABaC Restaurant Hotel Barcelona GL Monumento,41.410694,2.136294,8.464516
9,AC Hotel Barcelona Forum a Marriott Lifestyle ...,41.410131,2.218805,8.001384
10,AC Hotel Diagonal L Illa a Marriott Lifestyle ...,41.389961,2.135684,8.398214
11,AC Hotel Irla a Marriott Lifestyle Hotel,41.394818,2.143470,8.125000
12,AC Hotel Milano a Marriott Lifestyle Hotel,45.485180,9.183119,8.202778
13,AC Hotel Paris Porte Maillot by Marriott,48.882005,2.281854,8.425333
14,AC Hotel Sants a Marriott Lifestyle Hotel,41.377558,2.138469,7.921978
15,AC Hotel Victoria Suites a Marriott Lifestyle ...,41.389348,2.120976,8.828889
16,ADI Doria Grand Hotel,45.485372,9.211584,8.388435
17,ADI Hotel Poliziano Fiera,45.483717,9.164937,8.042991
18,ARCOTEL Kaiserwasser Superior,48.231915,16.417026,8.465035
19,ARCOTEL Wimberger,48.200600,16.338633,7.947651
20,AZIMUT Hotel Vienna,48.183479,16.376277,8.269880
21,Abba Garden,41.385472,2.101884,8.037600
22,Abba Sants,41.382578,2.140010,8.368333
23,Acad mie H tel Saint Germain,48.855263,2.330590,9.064706
24,Acca Palace,45.509997,9.173994,8.590909
25,Ace Hotel London Shoreditch,51.525416,-0.077285,8.683074
26,Acevi Villarroel,41.385378,2.156723,7.651420
27,Acta Atrium Palace,41.390913,2.170698,8.650437
28,Acta CITY47,41.383515,2.140740,8.185039
29,Admiral Hotel,45.480515,9.160063,7.130769
...,...,...,...,...
1447,Vincci Gala,41.389526,2.174714,8.742515
1448,Vincci Mae,41.393394,2.146132,8.995283
1449,Vincci Maritimo,41.408205,2.212463,8.210787
1450,W Amsterdam,52.372787,4.890006,8.303271
1451,W Barcelona,41.368437,2.190153,8.412348
1452,W London Leicester Square,51.510843,-0.131429,8.312360
1453,W Paris Op ra,48.871970,2.331601,8.307500
1454,W12 Rooms,51.504533,-0.219117,8.745926
1455,Waldorf Astoria Amsterdam,52.364768,4.896945,9.535211
1456,Waldorf Madeleine,48.871583,2.322485,8.608541
1457,Warwick Paris Former Warwick Champs Elysees,48.872202,2.303087,8.073236
1458,Washington Mayfair Hotel,51.506024,-0.151078,7.909442
1459,WestCord Art Hotel Amsterdam 4 stars,52.392490,4.868382,8.629764
1460,WestCord Fashion Hotel Amsterdam,52.357655,4.844576,8.896554
1461,Westside Arc de Triomphe Hotel,48.881174,2.294834,8.165529
1462,Wilson Boutique Hotel,41.394403,2.150194,8.782759
1463,Windermere Hotel,51.490372,-0.145922,8.950526
1464,Windsor Hotel Milano,45.479459,9.195143,8.285977
1465,Windsor Opera,48.873485,2.348511,8.088235
1466,Worldhotel Cristoforo Colombo,45.475884,9.205791,8.538477
1467,XO Hotel,48.882749,2.298278,8.823077
1468,Zenit Barcelona,41.394920,2.146859,8.081013
1469,Zenit Borrell,41.385987,2.151402,7.590476
1470,art otel Amsterdam,52.377743,4.897057,8.989114
1471,citizenM Amsterdam,52.341943,4.875960,8.770289
1472,citizenM London Bankside,51.505151,-0.100472,9.112261
1473,citizenM London Shoreditch,51.524137,-0.078698,9.092005
1474,citizenM Tower of London,51.510237,-0.076443,9.135591
1475,every hotel Piccadilly,51.510146,-0.131506,8.967782
1476,pentahotel Vienna,48.189974,16.356701,8.363566

In [7]:
#this function calculated distance between user specified location with all other hotels and return distance.
#https://stackoverflow.com/questions/19412462/getting-distance-between-two-points-based-on-latitude-longitude
import math
def distance(lat1, lon1, lat2, lon2):
    radius = 6371 # km 6371
    dlat = math.radians(lat2-lat1) #latitude converted into radians
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c

    return d

In [8]:
#this function will take loaction text as a input and return latitude and longitude for the location specified by the user
#reference:https://geopy.readthedocs.io/en/stable/
from geopy.geocoders import Nominatim
def getlatLng(Location):
    geolocator = Nominatim()
    location = geolocator.geocode(Location)
    return location.latitude, location.longitude

In [9]:
#this is input location Effiel tower given by user to get near by recommended hotel
lat2,lon2 = getlatLng("Eiffel Tower")

In [11]:
#in this cell different hotels latitude and longitude are passed in distance function with user specified location's longitude and latitude
df = []
for lat1,lon1,hotel,rating in zip(Hotel_And_Score.lat,Hotel_And_Score.lng,Hotel_And_Score.Hotel_Name,Hotel_And_Score.Reviewer_Score):
     dist = distance(lat1,lon1,lat2,lon2)
     df.append({'key': hotel,'value': dist,'value1':rating})

In [12]:
#converting list into dataframe
Hotel_distance = pd.DataFrame(df)

In [13]:
Hotel_distance

                                                    key        value    value1
0                                    11 Cadogan Gardens   341.135094  8.845283
1                                              1K Hotel     5.259317  7.861486
2                    25hours Hotel beim MuseumsQuartier  1036.337107  8.983309
3                                                    41   340.997822  9.711650
4                    45 Park Lane Dorchester Collection   342.062733  9.603571
5                                            88 Studios   343.497043  8.489107
6                                     9Hotel Republique     5.032567  8.743716
7                                     A La Villa Madame     2.903667  8.853659
8          ABaC Restaurant Hotel Barcelona GL Monumento   828.223984  8.464516
9     AC Hotel Barcelona Forum a Marriott Lifestyle ...   828.215388  8.001384
10    AC Hotel Diagonal L Illa a Marriott Lifestyle ...   830.529930  8.398214
11             AC Hotel Irla a Marriott Lifestyle Hotel   829.981060  8.125000
12           AC Hotel Milano a Marriott Lifestyle Hotel   641.322218  8.202778
13             AC Hotel Paris Porte Maillot by Marriott     2.797563  8.425333
14            AC Hotel Sants a Marriott Lifestyle Hotel   831.905742  7.921978
15    AC Hotel Victoria Suites a Marriott Lifestyle ...   830.616107  8.828889
16                                ADI Doria Grand Hotel   643.052763  8.388435
17                            ADI Hotel Poliziano Fiera   640.310561  8.042991
18                        ARCOTEL Kaiserwasser Superior  1040.448715  8.465035
19                                    ARCOTEL Wimberger  1035.272478  7.947651
20                                  AZIMUT Hotel Vienna  1038.335092  8.269880
21                                          Abba Garden   831.072811  8.037600
22                                           Abba Sants   831.345834  8.368333
23                         Acad mie H tel Saint Germain     2.661371  9.064706
24                                          Acca Palace   639.057520  8.590909
25                          Ace Hotel London Shoreditch   341.225998  8.683074
26                                     Acevi Villarroel   831.016485  7.651420
27                                   Acta Atrium Palace   830.387607  8.650437
28                                          Acta CITY47   831.240793  8.185039
29                                        Admiral Hotel   640.233533  7.130769
...                                                 ...          ...       ...
1447                                        Vincci Gala   830.538188  8.742515
1448                                         Vincci Mae   830.136362  8.995283
1449                                    Vincci Maritimo   828.433150  8.210787
1450                                        W Amsterdam   431.506205  8.303271
1451                                        W Barcelona   832.870361  8.412348
1452                          W London Leicester Square   341.761648  8.312360
1453                                      W Paris Op ra     3.112785  8.307500
1454                                          W12 Rooms   344.362115  8.745926
1455                          Waldorf Astoria Amsterdam   430.913785  9.535211
1456                                  Waldorf Madeleine     2.526924  8.608541
1457       Warwick Paris Former Warwick Champs Elysees      1.672677  8.073236
1458                           Washington Mayfair Hotel   342.013251  7.909442
1459               WestCord Art Hotel Amsterdam 4 stars   432.833577  8.629764
1460                   WestCord Fashion Hotel Amsterdam   428.642905  8.896554
1461                     Westside Arc de Triomphe Hotel     2.548027  8.165529
1462                              Wilson Boutique Hotel   830.019837  8.782759
1463                                   Windermere Hotel   340.343891  8.950526
1464                               Windsor Hotel Milano   642.452211  8.285977
1465                                      Windsor Opera     4.298239  8.088235
1466                      Worldhotel Cristoforo Colombo   643.350264  8.538477
1467                                           XO Hotel     2.737045  8.823077
1468                                    Zenit Barcelona   829.965943  8.081013
1469                                      Zenit Borrell   830.954254  7.590476
1470                                 art otel Amsterdam   432.211769  8.989114
1471                                 citizenM Amsterdam   428.007267  8.770289
1472                           citizenM London Bankside   340.111639  9.112261
1473                         citizenM London Shoreditch   341.153327  9.092005
1474                           citizenM Tower of London   339.744076  9.135591
1475                             every hotel Piccadilly   341.698223  8.967782
1476                                  pentahotel Vienna  1036.785511  8.363566

[1477 rows x 3 columns]

In [14]:
#renaming column names.
Hotel_distance = Hotel_distance.rename(index=str, columns={"key": "Hotels", "value": "Distance","value1":"Ratings"})

In [15]:
Hotel_distance

                                                 Hotels     Distance   Ratings
0                                    11 Cadogan Gardens   341.135094  8.845283
1                                              1K Hotel     5.259317  7.861486
2                    25hours Hotel beim MuseumsQuartier  1036.337107  8.983309
3                                                    41   340.997822  9.711650
4                    45 Park Lane Dorchester Collection   342.062733  9.603571
5                                            88 Studios   343.497043  8.489107
6                                     9Hotel Republique     5.032567  8.743716
7                                     A La Villa Madame     2.903667  8.853659
8          ABaC Restaurant Hotel Barcelona GL Monumento   828.223984  8.464516
9     AC Hotel Barcelona Forum a Marriott Lifestyle ...   828.215388  8.001384
10    AC Hotel Diagonal L Illa a Marriott Lifestyle ...   830.529930  8.398214
11             AC Hotel Irla a Marriott Lifestyle Hotel   829.981060  8.125000
12           AC Hotel Milano a Marriott Lifestyle Hotel   641.322218  8.202778
13             AC Hotel Paris Porte Maillot by Marriott     2.797563  8.425333
14            AC Hotel Sants a Marriott Lifestyle Hotel   831.905742  7.921978
15    AC Hotel Victoria Suites a Marriott Lifestyle ...   830.616107  8.828889
16                                ADI Doria Grand Hotel   643.052763  8.388435
17                            ADI Hotel Poliziano Fiera   640.310561  8.042991
18                        ARCOTEL Kaiserwasser Superior  1040.448715  8.465035
19                                    ARCOTEL Wimberger  1035.272478  7.947651
20                                  AZIMUT Hotel Vienna  1038.335092  8.269880
21                                          Abba Garden   831.072811  8.037600
22                                           Abba Sants   831.345834  8.368333
23                         Acad mie H tel Saint Germain     2.661371  9.064706
24                                          Acca Palace   639.057520  8.590909
25                          Ace Hotel London Shoreditch   341.225998  8.683074
26                                     Acevi Villarroel   831.016485  7.651420
27                                   Acta Atrium Palace   830.387607  8.650437
28                                          Acta CITY47   831.240793  8.185039
29                                        Admiral Hotel   640.233533  7.130769
...                                                 ...          ...       ...
1447                                        Vincci Gala   830.538188  8.742515
1448                                         Vincci Mae   830.136362  8.995283
1449                                    Vincci Maritimo   828.433150  8.210787
1450                                        W Amsterdam   431.506205  8.303271
1451                                        W Barcelona   832.870361  8.412348
1452                          W London Leicester Square   341.761648  8.312360
1453                                      W Paris Op ra     3.112785  8.307500
1454                                          W12 Rooms   344.362115  8.745926
1455                          Waldorf Astoria Amsterdam   430.913785  9.535211
1456                                  Waldorf Madeleine     2.526924  8.608541
1457       Warwick Paris Former Warwick Champs Elysees      1.672677  8.073236
1458                           Washington Mayfair Hotel   342.013251  7.909442
1459               WestCord Art Hotel Amsterdam 4 stars   432.833577  8.629764
1460                   WestCord Fashion Hotel Amsterdam   428.642905  8.896554
1461                     Westside Arc de Triomphe Hotel     2.548027  8.165529
1462                              Wilson Boutique Hotel   830.019837  8.782759
1463                                   Windermere Hotel   340.343891  8.950526
1464                               Windsor Hotel Milano   642.452211  8.285977
1465                                      Windsor Opera     4.298239  8.088235
1466                      Worldhotel Cristoforo Colombo   643.350264  8.538477
1467                                           XO Hotel     2.737045  8.823077
1468                                    Zenit Barcelona   829.965943  8.081013
1469                                      Zenit Borrell   830.954254  7.590476
1470                                 art otel Amsterdam   432.211769  8.989114
1471                                 citizenM Amsterdam   428.007267  8.770289
1472                           citizenM London Bankside   340.111639  9.112261
1473                         citizenM London Shoreditch   341.153327  9.092005
1474                           citizenM Tower of London   339.744076  9.135591
1475                             every hotel Piccadilly   341.698223  8.967782
1476                                  pentahotel Vienna  1036.785511  8.363566

[1477 rows x 3 columns]

In [16]:
#sorted the distance column to get top 10 recommended hotel with distance and rating
Hotel_distance.sort_values(['Distance','Ratings'],ascending=[True,False]).head(10)

                                Hotels  Distance   Ratings
1155         Pullman Paris Tour Eiffel  0.329445  8.601064
978   Mercure Paris Centre Tour Eiffel  0.409955  7.865110
269                         Derby Alma  0.515151  9.053571
1231            Shangri La Hotel Paris  0.610981  9.102174
300                   Eiffel Trocad ro  0.689919  7.999219
751                   Hotel Sezz Paris  0.699652  8.050000
879                  Le Marquis Eiffel  0.775675  8.776033
425                H tel Juliana Paris  0.808269  8.577515
470            H tel de la Bourdonnais  0.819728  8.760221
849                La Clef Tour Eiffel  0.834632  8.952063